name: Go Test Build and Deploy

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1
      
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v -o bmi-api ./cmd/api

    - uses: actions/upload-artifact@v3
      with:
          name: bmi-api-artifact
          path: ./bmi-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: bmi-api-artifact
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./bmi-api
           target: "/home/${{ secrets.USERNAME }}/bmi-api"

      - name: Start Bmi api 
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           script: |
               cd /home/${{ secrets.USERNAME }}/bmi-api
               chmod +x bmi-api
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop bmi-api.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl start bmi-api.service 
               echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx

 
